import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { AnalysisNotifications, validateSubscription } from '../src/analysis-notifications.mjs';
const sub={endpoint:'https://fcm.googleapis.com/fcm/send/example',keys:{p256dh:'a'.repeat(87),auth:'a'.repeat(22)}};
async function fixture(t,send){const root=await fs.mkdtemp(path.join(os.tmpdir(),'sba-notifications-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));await fs.mkdir(path.join(root,'r'));const file=path.join(root,'r','match.json');let counter=0;const write=async(complete=true)=>{await fs.writeFile(file,JSON.stringify({deathAnalysis:complete?{summary:`report${++counter}`} : null,deathAnalysisState:{status:complete?'complete':'report'}}));};await write();const opts={stateFile:path.join(root,'push.json'),analysisRoot:root,store:{list:()=>[{id:'r',fileName:'movie.mp4',matches:[{number:1,analysisUrl:'/api/analysis/r/match.json'}]}]},send};const service=new AnalysisNotifications(opts);await service.load();return {service,write,opts};}
test('existing results are quiet; completed AI reports notify once with the subscribed mount; restart preserves registration',async t=>{const sent=[];const {service,write,opts}=await fixture(t,async(s,p)=>sent.push(JSON.parse(p)));service.subscribe(sub,'/sba');await service.scan();assert.equal(sent.length,0);await write(false);await service.scan();assert.equal(sent.length,0);await write();await service.scan();assert.equal(sent.length,1);assert.equal(sent[0].url,'/sba/?recording=r&match=1');await service.scan();assert.equal(sent.length,1);const restored=new AnalysisNotifications(opts);await restored.load();await restored.scan();assert.equal(sent.length,1);assert.equal(Object.keys(restored.state.subscriptions).length,1);assert.equal(restored.state.keys.privateKey,service.state.keys.privateKey);});
test('transient failures survive restart and expired subscriptions are removed',async t=>{let fail=true;const {service,write,opts}=await fixture(t,async()=>{if(fail)throw {statusCode:503};});service.subscribe(sub,'');await write();await service.scan();assert.equal(service.state.pending.length,1);const restored=new AnalysisNotifications(opts);await restored.load();assert.equal(restored.state.pending.length,1);fail=false;restored.state.pending[0].next=0;await restored.flush();assert.equal(restored.state.pending.length,0);restored.send=async()=>{throw {statusCode:410};};await write();await restored.scan();assert.equal(Object.keys(restored.state.subscriptions).length,0);});
test('unsubscribed devices receive no pending notifications and arbitrary URLs are refused',async t=>{const {service}=await fixture(t,async()=>{});service.subscribe(sub,'/sba');service.unsubscribe(sub.endpoint);assert.equal(Object.keys(service.state.subscriptions).length,0);for(const endpoint of ['http://localhost/a','https://127.0.0.1/a','https://fcm.googleapis.com.evil.test/a','https://fcm.googleapis.com:444/a'])assert.throws(()=>validateSubscription({...sub,endpoint}));});

import http from 'node:http';
import { notificationRoute } from '../src/notification-routes.mjs';
import webpush from 'web-push';
import { createECDH, randomBytes } from 'node:crypto';
test('push payload can be encrypted with the persisted VAPID keys',async t=>{const {service}=await fixture(t,async()=>{});const ec=createECDH('prime256v1');ec.generateKeys();const valid={...sub,keys:{p256dh:ec.getPublicKey().toString('base64url'),auth:randomBytes(16).toString('base64url')}};const details=webpush.generateRequestDetails(valid,JSON.stringify({title:'完了'}),{vapidDetails:{subject:'https://github.com/kazurego7/splatoon3-battle-analyzer',...service.state.keys}});assert.ok(details.headers.Authorization);assert.ok(details.body.length>0);});
test('notification API rejects cross-origin registration and returns only public key',async t=>{const {service}=await fixture(t,async()=>{});const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host}`);req.appBasePath='/sba';await notificationRoute(req,res,url,service);});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>{server.closeAllConnections();server.close(resolve);}));const origin=`http://127.0.0.1:${server.address().port}`;assert.deepEqual(await(await fetch(origin+'/api/notifications')).json(),{publicKey:service.state.keys.publicKey});const options={method:'POST',headers:{origin:'https://evil.test','Content-Type':'application/json'},body:JSON.stringify(sub)};assert.equal((await fetch(origin+'/api/notifications',options)).status,403);options.headers.origin=origin;assert.equal((await fetch(origin+'/api/notifications',options)).status,200);assert.equal(Object.values(service.state.subscriptions)[0].base,'/sba');assert.equal((await fetch(origin+'/api/notifications',{...options,method:'DELETE',body:JSON.stringify({endpoint:sub.endpoint})})).status,200);assert.equal(Object.keys(service.state.subscriptions).length,0);});

import vm from 'node:vm';
test('service worker displays push while pages are closed and opens the correct mount on click',async()=>{const source=await fs.readFile(new URL('../public/sw.js',import.meta.url),'utf8');const handlers={},shown=[],opened=[];const context={URL,self:{registration:{scope:'https://pc.example/sba/',showNotification:async(title,options)=>shown.push({title,...options})},location:{origin:'https://pc.example'},addEventListener:(name,fn)=>handlers[name]=fn,clients:{matchAll:async()=>[],openWindow:async url=>opened.push(url)}}};vm.runInNewContext(source,context);let done;handlers.push({data:{json:()=>({title:'AI完了',body:'試合01',url:'/sba/?recording=r&match=1'})},waitUntil:p=>done=p});await done;assert.equal(shown[0].title,'AI完了');assert.equal(shown[0].icon,'/sba/icons/app-icon-192.png');handlers.notificationclick({notification:{data:shown[0].data,close(){}},waitUntil:p=>done=p});await done;assert.equal(opened[0],'https://pc.example/sba/?recording=r&match=1');handlers.notificationclick({notification:{data:{url:'https://evil.test/'},close(){}},waitUntil:p=>done=p});await done;assert.equal(opened[1],'https://pc.example/sba/');});
